name: CI-build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  windows:
    strategy:
      matrix:
        os-version: ['x64', 'arm64']

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: build
        run: |
          pnpm install
          pnpm run build:win-${{ matrix.os-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd .\dist\win-unpacked
          7z a -r Final2x-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd .\dist\win-arm64-unpacked
          7z a -r Final2x-windows-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-setup
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-windows-${{ matrix.os-version }}-setup
          path: dist/*.exe

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-unpacked/*.7z

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-windows-${{ matrix.os-version }}-unpacked
          path: dist/win-arm64-unpacked/*.7z

  macos:
    strategy:
      matrix:
        os-version: ['x64', 'arm64']

    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: build
        run: |
          pnpm install
          pnpm run build:mac-${{ matrix.os-version }}
        env:
          ARCH: ${{ matrix.os-version }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked-x64
        if: matrix.os-version == 'x64'
        run: |
          cd ./dist/mac
          7z a -r Final2x-macos-${{ matrix.os-version }}-unpacked.7z *

      - name: zip-unpacked-arm64
        if: matrix.os-version == 'arm64'
        run: |
          cd ./dist/mac-arm64
          7z a -r Final2x-macos-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-dmg
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-macos-${{ matrix.os-version }}-dmg
          path: dist/*.dmg

      - name: upload-unpacked-x64
        if: matrix.os-version == 'x64'
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-macos-${{ matrix.os-version }}-unpacked
          path: dist/mac/*.7z

      - name: upload-unpacked-arm64
        if: matrix.os-version == 'arm64'
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-macos-${{ matrix.os-version }}-unpacked
          path: dist/mac-arm64/*.7z

  linux-pip:
    strategy:
      matrix:
        os-version: ['x64']

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: build
        run: |
          pnpm install
          pnpm run build:linux-${{ matrix.os-version }}
        env:
          SKIP_DOWNLOAD_CORE: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: zip-unpacked
        run: |
          cd ./dist/linux-unpacked
          7z a -r Final2x-linux-pip-${{ matrix.os-version }}-unpacked.7z *

      - name: upload-snap
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-snap
          path: dist/*.snap

      - name: upload-AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-AppImage
          path: dist/*.AppImage

      - name: upload-deb
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-deb
          path: dist/*.deb

      - name: upload-unpacked
        uses: actions/upload-artifact@v3
        with:
          name: Final2x-linux-pip-${{ matrix.os-version }}-unpacked
          path: dist/linux-unpacked/*.7z
